# Site Settings
locale                   : "en-US"
title                    : "Dimitar Georgiev"
title_separator          : " - "
name                     : &name "Dimitar Georgiev"
description              : &description "My personal website"
url                      : "https://dimgeorgievv.github.io"
repository               : "dimgeorgievv/dimgeorgievv.github.io"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# Site Author
author:
  name             : "Dimitar Georgiev"
  avatar           : "photo.png"
  bio              : "PhD student in AI & ML"
  location         : 
  employer         : "Imperial College London"
  googlescholar    : "https://scholar.google.com/citations?view_op=list_works&hl=en&user=v9OuyKAAAAAJ&gmla=AJsN-F4tTAXexxnHVMBEXdYeiViSdWtaaKxjHHX7_wszOoJBTOFkKp6rc6pbMS5Fect0c4lAVR6j50jUGtLIvc39dfgZ5giCCAryQKXj-Ci5MMuSv1PDNoY&gmla=AJsN-F4RSdAZHgumTKHtUXddxrHzESuHKiJnMjv8HyPHSpYKilbY8oxILDkirHb5ooSxb7kb8lFuMmc9Ye_Jqiy0nvtKRjPzrSbphIBU6ISNA3yBvUx3Agk&sciund=14755906128220348560&gmla=AJsN-F68dLlTYYYu2AR9Pa8dAZTK11r6zB27LANM0eKAlvw3jb_cxP7_V-0CeQIFPc-4_A6flJeOBfBzCM3j1PXzdfBjSXOYESK2tHUBSIb_sRQr_icZFJI&sciund=2673617738422828361&gmla=AJsN-F6oc97BuD8OLwIWr3UcNRyw-DVUjZJUlv-lsQAXX8Q6Kc2ensctW9dpbrGiNdIb4u-w8x1eG7p8lqsYThU64WB7ONm635QOAuwmhbJtQze2Ip1hKt4&sciund=470730053679005797&gmla=AJsN-F7YMvOl_P28yil5tIFcNUp6jKUYOoomJJYAD-xbEKfUsZsnTx49ryKsWT5oCKdHxDIo_ltj9VLef6othyRCDH_zAbaf_609vA5CqMM-3XVO9Y6dyRM&sciund=13617952787924617685"
  email            : 
  researchgate     : "https://www.researchgate.net/profile/Dimitar-Georgiev-11"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "dgeorgiev21"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : "dimitar-georgievv"
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "dimgeorgievv"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
    

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/London


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
